spring.jackson.serialization.write-dates-as-timestamps=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
spring.jackson.default-property-inclusion=non_absent
# file upload size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB